image: "registry.gitlab.com/arvamer/gilrs"

before_script:
  - git submodule init
  - git submodule update
  - rustc --version && cargo --version

cache:
  key: "$CI_BUILD_REF"
  paths:
    - $HOME/.cargo
    - target

build:x86_64-unknown-linux-gnu:
  stage: build
  script:
    - cargo build --verbose

test:x86_64-unknown-linux-gnu:
  stage: test
  script:
    - cargo test --verbose

build:x86_64-pc-windows-gnu:
  stage: build
  script:
    - cargo build --verbose --target=x86_64-pc-windows-gnu

pages:
  stage: deploy
  script:
  - cargo doc
  # Remove libc from documentation to speed up deploy
  - rm -r target/doc/libc
  - rm -r target/doc/src/libc
  - mkdir public
  - mkdir public/img
  - mv target/doc public
  - mv controller.svg public/img/
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
