image: "scorpil/rust:stable"

before_script:
- apt-get update -yqq
- apt-get install -yqq pkg-config libudev-dev git
- git submodule init
- git submodule update

test:cargo:
  script:
  - rustc --version && cargo --version
  - cargo test --verbose --jobs 1 --release

pages:
  script:
  - cargo doc
  - mkdir public
  - mv target/doc public
  artifacts:
    paths:
      - public
  only:
    - master
