[package]
name = "gilrs"
version = "0.4.2"
authors = ["Arvamer <arvamer@gmail.com>"]
license = "Apache-2.0/MIT"
exclude = ["controller.svg"]
description = "Game Input Library for Rust"
documentation = "https://docs.rs/gilrs/"
repository = "https://gitlab.com/Arvamer/gilrs"
readme = "README.md"
keywords = ["gamepad", "joystick", "input"]


[dependencies]
vec_map = "0.6"
uuid = "0.2"
log = "0.3"

[dev-dependencies]
env_logger = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
libudev-sys = "0.1"
libc = "0.2"
nix = "0.8.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.2"
xinput-sys = "0.2"
