[package]
name = "gilrs"
version = "0.1.0"
authors = ["Arvamer <arvamer@gmail.com>"]

[dependencies]
vec_map = "0.6"

[target.'cfg(target_os = "linux")'.dependencies]
libudev-sys = "0.1"
libc = "0.2"
ioctl = "0.3"
