single_line_if_else_max_width = 80
array_horizontal_layout_threshold = 6
condense_wildcard_suffixes = true
error_on_line_overflow = false
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
struct_lit_width = 40
struct_variant_width = 60
use_try_shorthand = true
format_strings = true
